server:
  port: 2000

spring:
  application:
    name: chat
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: none
      base-url: http://127.0.0.1:1234
      embedding:
        api-key: ""
        options:
          model: text-embedding-nomic-embed-text-v2-moe
          dimensions: 768
      chat:
        api-key: ""
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 1000
        schema-validation: true
        table-name: vector_store


