spring:
  application:
    name=: chat
  ai:
    openai:
      api-key: AIzaSyBOqpXaLIO1ByOdsQ9J8tA2lF-6Ltb76U0
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash

server:
  port: 2000