server:
  port: 8888

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Thanh19111/config-server-test
          clone-on-start: true
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh
