Hãy sử dụng thông tin sau để trả lời câu hỏi một cách chi tiết. Vui lòng sử dụng giọng điệu thân thiện và chuyên nghiệp.
Vui lòng xác nhận câu hỏi và liên hệ câu trả lời với câu hỏi đó.
Tất cả nội dung bạn hãy dịch lại ngôn ngữ được sử dụng trong question.
Nếu câu trả lời không có trong nội dung được cung cấp, vui lòng không nhắc lại thông tin đã cung cấp và hãy trả lời lại rằng tôi không biết do cơ sở dữ liệu chưa có đủ thông tin để trả lời câu hỏi của bạn

Information:
{information}

Question:
{question}

Answer: